apply plugin: 'com.android.application'

android {
    compileSdk 35
    defaultConfig {
        applicationId "com.genymobile.scrcpy"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 14
        versionName "1.12.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                abiFilters 'arm64-v8a', 'armeabi-v7a'
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
    sourceSets {
        main {
            java.srcDirs 'src/java'
            jniLibs.srcDirs 'libs/libturbojpeg/prebuilt'
            jniLibs.srcDirs = ['libs/libturbojpeg/prebuilt'] // 确保路径正确
        }
    }
    buildFeatures {
        buildConfig true
        aidl true
    }
    namespace 'com.genymobile.scrcpy'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.so'])
    testImplementation 'junit:junit:4.12'
    implementation 'commons-cli:commons-cli:1.4'
}
tasks.register("prepareKotlinBuildScriptModel"){}

apply from: "$project.rootDir/config/android-checkstyle.gradle"
